### PR TITLE
fix: fix getting printers and default printer on non-english systems

### PR DESCRIPTION
**Pull request by leMaik**
On non-english systems, the printer lines start with the localized word for "printer", which breaks parsing. As a fix, this PR enforces an english locale.

### CODE REVIEW

**Comment by artiebits** [comment]
hi, thanks for the PR! I can merge this PR once you fix the tests

**Comment by leMaik** [comment]
I didn't really break the tests in the first place, but I'll be happy to look into it.

```
node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
The command "npm config set spin false" failed and exited with 1 during .
```

**Comment by artiebits** [comment]
oh, I was too fast making an assumption, sorry for it.
downgrading to node 17, or moving to github actions should help. both are fine by me, let me know if you are interested in doing it!

**Comment by artiebits** [comment]
@leMaik Could you please rebase your branch? I downgraded the Node version in TravisCI to 17

**Comment by artiebits** [comment]
Hi @leMaik would you be able to fix the broken tests?

**Pull request closed without merging**
